/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penerimaan_karyawan;

import static Models.Config.conn;
import java.awt.Color;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author psw
 */
public class ShowDataKaryawan extends javax.swing.JFrame {
    
    String ex_data_id_karyawan, ex_data_nama_karyawan, ex_data_telp_karyawan, ex_data_alamat_karyawan, ex_data_dept_karyawan, ex_data_jabatan_karyawan, ex_data_posisi_karyawan, ex_data_pt_karyawan, ex_data_status_karyawan;
    PreparedStatement ps = null;
    ResultSet rs = null;
        DefaultTableModel tablemodelKaryawan;
    ImageIcon sucess = new ImageIcon(getClass().getResource("/Icon/checked.png"));
    ImageIcon invalid = new ImageIcon(getClass().getResource("/Icon/cancel.png"));
    ImageIcon warning = new ImageIcon(getClass().getResource("/Icon/warning.png"));
    
    public ShowDataKaryawan() {
        initComponents();
        getCBclient();
        getCBposisi();
        ex_showkaryawan_text.setVisible(false);
    }
    
    protected void getCBposisi(){
        String sql = "SELECT * FROM client";      
        try {
            ps = Models.Config.Conn().prepareStatement(sql);
            rs=ps.executeQuery();
            while (rs.next()) {                
                String Posisi = rs.getString("nama");
                ex_pt_kar.addItem(Posisi);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat"+e.getMessage(), "Peringatan", HEIGHT);
        }
    }
    
    protected void getCBclient(){
        String sql = "SELECT * FROM posisi";      
        try {
            ps = Models.Config.Conn().prepareStatement(sql);
            rs=ps.executeQuery();
            while (rs.next()) {                
                String Posisi = rs.getString("posisi");
                ex_sdk_posisi.addItem(Posisi);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat"+e.getMessage(), "Peringatan", HEIGHT);
        }
    }
    
//    protected void TableKaryawan() {
//        Object[] Baris = {"ID", "Nama", "Telp", "Alamat", "Department", "Jabatan", "Posisi", "Perusahaan", "Tgl.Join", "Status"};
//        tablemodelKaryawan = new DefaultTableModel(null, Baris);
//
//        try {
//            String sql = "SELECT `id`, `nama`, `telp`, `alamat`, `department`, `jabatan`, `posisi`, `nama_pt`, `tgl_gabung`, `status` FROM `karyawan` order by status asc";
//            Statement stat = Models.Config.Conn().createStatement();
//            ResultSet hasil = stat.executeQuery(sql);
//            while (hasil.next()) {
//                tablemodelKaryawan.addRow(new Object[]{
//                    hasil.getString(1),
//                    hasil.getString(2),
//                    hasil.getString(3),
//                    hasil.getString(4),
//                    hasil.getString(5),
//                    hasil.getString(6),
//                    hasil.getString(7),
//                    hasil.getString(8),
//                    hasil.getString(9),
//                    hasil.getString(10)
//                });
//            }
//            tab.setModel(tablemodelKaryawan);
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "Gagal Posisi Master: " + e);
//        }
//    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ex_id_kar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ex_nama_kar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ex_telp_kar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ex_alamat_kar = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        ex_pt_kar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ex_dept_kar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ex_jabatan_kar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ex_status_kar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        ex_sdk_posisi = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ex_showkaryawan_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ID Karyawan");

        ex_id_kar.setEnabled(false);

        jLabel2.setText("Nama Karyawan");

        ex_nama_kar.setEnabled(false);

        jLabel3.setText("No.Telp");

        jLabel4.setText("Alamat");

        ex_alamat_kar.setColumns(20);
        ex_alamat_kar.setRows(5);
        jScrollPane1.setViewportView(ex_alamat_kar);

        jLabel5.setText("Perusahaan");

        ex_pt_kar.setPreferredSize(new java.awt.Dimension(56, 30));

        jLabel6.setText("Department");

        ex_dept_kar.setPreferredSize(new java.awt.Dimension(59, 30));

        jLabel7.setText("Jabatan");

        ex_jabatan_kar.setPreferredSize(new java.awt.Dimension(59, 30));

        jLabel8.setText("Status");

        ex_status_kar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Probation", "Contract", "Permanent", "Non-Aktiv" }));
        ex_status_kar.setPreferredSize(new java.awt.Dimension(56, 30));

        jLabel9.setText("Posisi");

        ex_sdk_posisi.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ex_sdk_posisiPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(ex_telp_kar)
                    .addComponent(ex_nama_kar)
                    .addComponent(ex_id_kar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(ex_pt_kar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(ex_dept_kar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(ex_jabatan_kar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(ex_status_kar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(ex_sdk_posisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ex_id_kar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex_pt_kar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ex_nama_kar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex_dept_kar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ex_telp_kar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex_jabatan_kar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ex_sdk_posisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ex_status_kar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Simpan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ex_showkaryawan_text.setText("Pembaharuan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ex_showkaryawan_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ex_showkaryawan_text)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ex_sdk_posisiPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ex_sdk_posisiPopupMenuWillBecomeInvisible
//        String cb = (String)ex_sdk_posisi.getSelectedItem();
        
    }//GEN-LAST:event_ex_sdk_posisiPopupMenuWillBecomeInvisible

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if (ex_id_kar.getText().isEmpty() || ex_alamat_kar.getText().isEmpty() || ex_dept_kar.getText().isEmpty()
                || ex_jabatan_kar.getText().isEmpty() || ex_nama_kar.getText().isEmpty() || ex_pt_kar.getSelectedItem().equals("Pilih")
                || ex_sdk_posisi.getSelectedItem().equals("Pilih") || ex_status_kar.getSelectedItem().equals("Pilih") ||
                ex_telp_kar.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Belum Terpenuhi!", "Perhatian!", HEIGHT, warning);
        } else {
            try {
                String sql = "update karyawan set department=?,jabatan=?,posisi=?,nama_pt=?,status=?, status_data=? where id='" + ex_id_kar.getText() + "'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, ex_dept_kar.getText());
                stat.setString(2, ex_jabatan_kar.getText());
                stat.setString(3, ex_sdk_posisi.getSelectedItem().toString());
                stat.setString(4, ex_pt_kar.getSelectedItem().toString());
                stat.setString(5, ex_status_kar.getSelectedItem().toString());
                stat.setString(6, ex_showkaryawan_text.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Ubah!", "Berhasil!", HEIGHT, sucess);
                dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan!", "Perhatian!", HEIGHT, invalid);
            }
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowDataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea ex_alamat_kar;
    public javax.swing.JTextField ex_dept_kar;
    public javax.swing.JTextField ex_id_kar;
    public javax.swing.JTextField ex_jabatan_kar;
    public javax.swing.JTextField ex_nama_kar;
    public javax.swing.JComboBox<String> ex_pt_kar;
    public javax.swing.JComboBox<String> ex_sdk_posisi;
    private javax.swing.JLabel ex_showkaryawan_text;
    public javax.swing.JComboBox<String> ex_status_kar;
    public javax.swing.JTextField ex_telp_kar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
